---
# Script to Boostrap a New Fedora System

- hosts: localhost
  vars:
    fedora_release_version: 36
  tasks:
    - import_tasks: tasks/rpm-fusion.yml
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/dev-tools.yml
    - import_tasks: tasks/npm.yml
    - import_tasks: tasks/jetbrains-toolbox.yml
    - import_tasks: tasks/rustup.yml
    - import_tasks: tasks/productivity.yml
    - import_tasks: tasks/virtualization.yml
    - import_tasks: tasks/codecs.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/sublime-text.yml
    - import_tasks: tasks/1password.yml
    - import_tasks: tasks/games.yml
    - import_tasks: tasks/entertainment.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/gsettings.yml
    - import_tasks: tasks/fonts.yml
    - name: Print instructions to correct issue with ibus
      debug:
        msg: |
          Run the command 'ibus-setup' then Emoji -> Emoji annotation
          then delete the control + . option. This interferes with vscode
          quick actions.
