- hosts: all
  tasks:
    - include: tasks/essential.yml
    - include: tasks/dev-tools.yml
    - include: tasks/npm.yml
    - include: tasks/rustup.yml
    - include: tasks/productivity.yml
    - include: tasks/git.yml
    - include: tasks/neovim.yml
    - include: tasks/fish.yml
