---
# Install 1password and op cli

- name: Add 1password gpg key
  become: yes
  rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: Add 1password repo
  become: yes
  yum_repository:
    name: 1password
    description: https://downloads.1password.com/linux/keys/1password.asc
    baseurl: https://downloads.1password.com/linux/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

- name: Install 1password and 1password cli
  become: yes
  dnf:
    name: [1password, 1password-cli]
    state: present
  tags: [1password]
