---
- name: Install Development Tools (dnf)
  become: yes
  dnf:
    name:
      - '@Development Tools'
      - clang
      - llvm
      - lld
      - lldb
      - musl-devel
      - musl-clang
      - musl-gcc
      - cmake
      - ninja-build
      - fish
    state: installed
  tags: [devtools]

- name: Install Java and Gradle (sdkman)
  include_role:
    name: comcast.sdkman
  vars:
    sdkman_user: "{{ ansible_user_id }}"
    sdkman_group: "{{ ansible_user_id }}"
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: java, version: 17.0.3.fx-zulu }
      - { candidate: gradle, version: 7.4.2 }
  tags: [devtools, java]
