- name: Install Development Tools
  dnf:
    name:
      - clang
      - llvm
      - lld
      - lldb
      - musl-devel
      - musl-clang
      - musl-gcc
      - cmake
      - ninja-build
      - python3
    state: installed
