---
# Install Essentials

- name: Add charm repository
  become: yes
  yum_repository:
    name: charm
    description: Charm
    baseurl: https://repo.charm.sh/yum/
    enabled: yes
    gpgcheck: no

- name: Install Essentials
  become: yes
  dnf:
    name:
      - git
      - exa
      - bat
      - glow
    state: present
