---
- name: Check if git repo has already been cloned
  stat:
    path: '{{ ansible_env.HOME }}/.config/fish/functions/.git'
  register: git_repo_info

- name: Ensure fish functions folder does not exist
  file:
    name: '{{ ansible_env.HOME }}/.config/fish/functions'
    state: absent
  when: not git_repo_info.stat.exists

- name: Clone fish functions
  git:
    repo: https://github.com/doggodoge/fish-functions.git
    dest: '{{ ansible_env.HOME }}/.config/fish/functions'
  when: not git_repo_info.stat.exists
