---
# Install Steam and Lutris

- name: Install steam
  become: true
  dnf:
    name: steam
    state: present
  tags:
    - steam
    - games

- name: Install lutris
  become: true
  dnf:
    name: lutris
    state: present
  tags:
    - lutris
    - games
