---
# Set neovim config from template file

- name: Install VimPlug for NeoVim
  command:
    cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    creates: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim'

- name: Ensure neovim config path exists
  file:
    path: '{{ ansible_env.HOME }}/.config/nvim'
    state: directory

- name: Add neovim config
  copy:
    src: ../files/init.vim
    dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
  tags:
    - productivity
