---
- name: Ensure neovim config path exists
  file:
    path: '{{ ansible_env.HOME }}/.config/nvim'
    state: directory

- name: Add neovim config
  copy:
    src: ../files/init.vim
    dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
  tags:
    - productivity
