---
- name: Add rpm fusion free
  become: yes
  dnf:
    name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_release_version }}.noarch.rpm'
    state: present
    disable_gpg_check: true

- name: add rpm fusion non-free
  become: yes
  dnf:
    name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_release_version }}.noarch.rpm'
    state: present
    disable_gpg_check: true
