---
# Install Virtualization Tools

- name: Install virtualization tools
  become: true
  dnf:
    name:
      - '@Virtualization'
      - vagrant
      - vagrant-libvirt
      - qemu-user
      - qemu-user-static
    state: present
