---
# Install VSCode

- name: Add Microsoft rpm key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
    - vscode

- name: Add VS Code repository
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  tags:
    - vscode

- name: Install Visual Studio Code
  become: yes
  dnf:
    name: code
    state: present
  tags:
    - vscode
